create table if not exists users
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255)        not null,
    email VARCHAR(100) UNIQUE not null
);

CREATE TABLE IF NOT EXISTS items
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    available   BOOLEAN      NOT NULL,
    owner_id    INTEGER      NOT NULL,
    CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP    NOT NULL,
    end_time   TIMESTAMP    NOT NULL,
    item_id    INTEGER      NOT NULL,
    booker_id  INTEGER      NOT NULL,
    status     varchar(100) NOT NULL,
    CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT fk_booker FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE
);

create table if not exists comments
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id        INTEGER      NOT NULL,
    comment_author INTEGER      NOT NULL,
    create_date    TIMESTAMP    NOT NULL,
    comment_text   varchar(255) NOT NULL,
    CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT fk_booker FOREIGN KEY (comment_author) REFERENCES users (id) ON DELETE CASCADE
);